repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    # -   id: end-of-file-fixer
    # -   id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        verbose: true
        entry: mypy
        args:
          [
            --no-strict-optional,
            --show-traceback,
            --ignore-missing-imports,
            --follow-imports=silent,
            --show-error-codes,
          ]
        language: python
        language_version: python3.10
        additional_dependencies:
          - "sqlalchemy[mypy]"
          - "strawberry-graphql"
          - "types-cachetools"
          - "pydantic"
          - typing-extensions
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
