services:
  db:
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: plantapp

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
